/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.GraficoBot;
import Model.GraficosJuntos;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Charlie
 */
public class WindowInicio extends javax.swing.JFrame {

    /**
     * Creates new form WindowInicio
     */
    public WindowInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSpinnerFichasIniciales = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jSpinnerPartidas = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Niño elige");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("NIÑO ELIGE A VER CÓMO QUIERES JUGAR");

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUEGO MANUAL", "MI SÚPER BOT INTELIGENTE", "TABLA ESTRATEGIAS", "PLANTARSE TAL CUAL", "COMPARAR BOTS" }));
        jComboBox1.setSelectedIndex(4);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUEGO POR PASOS", "GRÁFICO TRAS X PARTIDAS" }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jSpinnerFichasIniciales.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jSpinnerFichasIniciales.setModel(new javax.swing.SpinnerNumberModel(30000, 100, null, 100));
        jSpinnerFichasIniciales.setToolTipText("");
        jSpinnerFichasIniciales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerFichasIniciales.setName(""); // NOI18N
        jSpinnerFichasIniciales.setValue(20000);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setText("FICHAS INICIALES");

        jButtonCancelar.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jSpinnerPartidas.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jSpinnerPartidas.setModel(new javax.swing.SpinnerNumberModel(50000, 50, null, 10));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setText("NÚMERO DE PARTIDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(jSpinnerFichasIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jSpinnerPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jSpinnerFichasIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        this.dispose();
        switch (jComboBox1.getSelectedItem().toString()) {
            case "JUEGO MANUAL":
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new WindowJuego(Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + "")).setVisible(true);
                    }
                });
                break;
            case "MI SÚPER BOT INTELIGENTE":
                if (jComboBox2.getSelectedItem().toString().equalsIgnoreCase("JUEGO POR PASOS")) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new WindowJuego(Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + ""), 1).setVisible(true);
                        }
                    });
                } else {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new GraficoBot(Integer.parseInt(jSpinnerPartidas.getValue().toString() + ""), Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + ""), 1);
                        }
                    });
                }
                break;
            case "PLANTARSE TAL CUAL":
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new GraficoBot(Integer.parseInt(jSpinnerPartidas.getValue().toString() + ""), Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + ""), 2);
                        }
                    });
                break;
            case "TABLA ESTRATEGIAS":
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new GraficoBot(Integer.parseInt(jSpinnerPartidas.getValue().toString() + ""), Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + ""), 3);
                        }
                    });
                break;
            case "COMPARAR BOTS":
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new GraficosJuntos(Integer.parseInt(jSpinnerPartidas.getValue().toString() + ""), Integer.parseInt(jSpinnerFichasIniciales.getValue().toString() + ""));
                        }
                    });
                break;
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 0) {
            jComboBox2.setEnabled(false);
            jSpinnerPartidas.setVisible(false);
            jLabel3.setVisible(false);
        } else if(jComboBox1.getSelectedIndex() >= 2){
            jComboBox2.setEnabled(false);
            jLabel3.setVisible(true);
            jSpinnerPartidas.setVisible(true);
            jSpinnerPartidas.setEnabled(true);
        }
        else {
            jComboBox2.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() == 0) {
            jLabel3.setVisible(false);
            jSpinnerPartidas.setVisible(false);
        } else {
            jLabel3.setVisible(true);
            jSpinnerPartidas.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinnerFichasIniciales;
    private javax.swing.JSpinner jSpinnerPartidas;
    // End of variables declaration//GEN-END:variables
}
