/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.JuegoBot;
import Model.JuegoManual;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Charlie
 */
public class WindowJuego extends javax.swing.JFrame {
    
    private int fichasIniciales;
    private JuegoManual juegoManualActual;
    private JuegoBot juegoBotActual;

    /**
     * Creates new form MainWindow
     * @param fichasIniciales
     */
    public WindowJuego(int fichasIniciales) {
        initComponents();
        jButtonNuevaApuesta.setVisible(false);
        this.setLocationRelativeTo(null);
        this.fichasIniciales = fichasIniciales;
        juegoManualActual = new JuegoManual(this);
        actualizarFichas();
    }
    
    public WindowJuego(int fichasIniciales, int x){
        switch(x){
            case 1: juegoBot(fichasIniciales); break;
        }
    }

    public int getFichasIniciales() {
        return fichasIniciales;
    }

    public JLabel getjLabelCrupier1() {
        return jLabelCrupier1;
    }

    public JLabel getjLabelCrupier2() {
        return jLabelCrupier2;
    }

    public JLabel getjLabelCrupier3() {
        return jLabelCrupier3;
    }

    public JLabel getjLabelCrupier4() {
        return jLabelCrupier4;
    }

    public JLabel getjLabelCrupier5() {
        return jLabelCrupier5;
    }

    public JLabel getjLabelCrupier6() {
        return jLabelCrupier6;
    }

    public JLabel getjLabelJugador1() {
        return jLabelJugador1;
    }

    public JLabel getjLabelJugador2() {
        return jLabelJugador2;
    }

    public JLabel getjLabelJugador3() {
        return jLabelJugador3;
    }

    public JLabel getjLabelJugador4() {
        return jLabelJugador4;
    }

    public JLabel getjLabelJugador5() {
        return jLabelJugador5;
    }

    public JLabel getjLabelJugador6() {
        return jLabelJugador6;
    }

    public JLabel getjLabelJugador10() {
        return jLabelJugador10;
    }

    public JLabel getjLabelJugador7() {
        return jLabelJugador7;
    }

    public JLabel getjLabelJugador8() {
        return jLabelJugador8;
    }

    public JLabel getjLabelJugador9() {
        return jLabelJugador9;
    }

    public JLabel getjLabelPuntMaquina() {
        return jLabelPuntMaquina;
    }

    public JLabel getjLabelPuntPerdedor() {
        return jLabelPuntPerdedor;
    }

    public JLabel getjLabelCrupier10() {
        return jLabelCrupier10;
    }

    public JLabel getjLabelCrupier7() {
        return jLabelCrupier7;
    }

    public JLabel getjLabelCrupier8() {
        return jLabelCrupier8;
    }

    public JLabel getjLabelCrupier9() {
        return jLabelCrupier9;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPuntPerdedor = new javax.swing.JLabel();
        jLabelPuntMaquina = new javax.swing.JLabel();
        jButtonApostarManual = new javax.swing.JButton();
        jButtonApostarBot = new javax.swing.JButton();
        jSpinnerApuesta = new javax.swing.JSpinner();
        jButtonPedir = new javax.swing.JButton();
        jButtonPlantarse = new javax.swing.JButton();
        jButtonNuevaApuesta = new javax.swing.JButton();
        jButtonNuevaApuestaBot = new javax.swing.JButton();
        jLabelFichasJug = new javax.swing.JLabel();
        jLabelFichasJugBot = new javax.swing.JLabel();
        jLabelTextFichas = new javax.swing.JLabel();
        jLabelJugador10 = new javax.swing.JLabel();
        jLabelJugador9 = new javax.swing.JLabel();
        jLabelJugador8 = new javax.swing.JLabel();
        jLabelJugador7 = new javax.swing.JLabel();
        jLabelJugador6 = new javax.swing.JLabel();
        jLabelJugador5 = new javax.swing.JLabel();
        jLabelJugador4 = new javax.swing.JLabel();
        jLabelJugador3 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabelCrupier10 = new javax.swing.JLabel();
        jLabelCrupier9 = new javax.swing.JLabel();
        jLabelCrupier8 = new javax.swing.JLabel();
        jLabelCrupier7 = new javax.swing.JLabel();
        jLabelCrupier6 = new javax.swing.JLabel();
        jLabelCrupier5 = new javax.swing.JLabel();
        jLabelCrupier4 = new javax.swing.JLabel();
        jLabelCrupier3 = new javax.swing.JLabel();
        jLabelCrupier2 = new javax.swing.JLabel();
        jLabelCrupier1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Blackjacksito");
        setMaximumSize(new java.awt.Dimension(1100, 800));
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPuntPerdedor.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        getContentPane().add(jLabelPuntPerdedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 50, 40));

        jLabelPuntMaquina.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        getContentPane().add(jLabelPuntMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 50, 40));

        jButtonApostarManual.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButtonApostarManual.setText("APOSTAR");
        jButtonApostarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarManualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApostarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 150, 40));

        jButtonApostarBot.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButtonApostarBot.setText("APOSTAR");
        jButtonApostarBot.setEnabled(false);
        jButtonApostarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarBotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApostarBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 150, 40));

        jSpinnerApuesta.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jSpinnerApuesta.setModel(new javax.swing.SpinnerNumberModel(200, 50, 5000, 10));
        getContentPane().add(jSpinnerApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 120, 40));

        jButtonPedir.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jButtonPedir.setText("PEDIR");
        jButtonPedir.setEnabled(false);
        jButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        jButtonPlantarse.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jButtonPlantarse.setText("PLANTARSE");
        jButtonPlantarse.setEnabled(false);
        jButtonPlantarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlantarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlantarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));

        jButtonNuevaApuesta.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jButtonNuevaApuesta.setText("NUEVA APUESTA");
        jButtonNuevaApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaApuestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevaApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 300, 40));

        jButtonNuevaApuestaBot.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jButtonNuevaApuestaBot.setText("NUEVA APUESTA");
        jButtonNuevaApuestaBot.setEnabled(false);
        jButtonNuevaApuestaBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaApuestaBotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevaApuestaBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 300, 40));

        jLabelFichasJug.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelFichasJug.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jLabelFichasJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 710, 100, 50));

        jLabelFichasJugBot.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelFichasJugBot.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jLabelFichasJugBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 710, 120, 50));

        jLabelTextFichas.setFont(new java.awt.Font("Comic Sans MS", 3, 20)); // NOI18N
        jLabelTextFichas.setText("FICHAS:");
        getContentPane().add(jLabelTextFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 110, 50));

        jLabelJugador10.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador10.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador10.setName(""); // NOI18N
        jLabelJugador10.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, -1, -1));

        jLabelJugador9.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador9.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador9.setName(""); // NOI18N
        jLabelJugador9.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));

        jLabelJugador8.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador8.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador8.setName(""); // NOI18N
        jLabelJugador8.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, -1));

        jLabelJugador7.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador7.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador7.setName(""); // NOI18N
        jLabelJugador7.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        jLabelJugador6.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador6.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador6.setName(""); // NOI18N
        jLabelJugador6.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));

        jLabelJugador5.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador5.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador5.setName(""); // NOI18N
        jLabelJugador5.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, -1, -1));

        jLabelJugador4.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador4.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador4.setName(""); // NOI18N
        jLabelJugador4.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        jLabelJugador3.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador3.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador3.setName(""); // NOI18N
        jLabelJugador3.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        jLabelJugador2.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador2.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador2.setName(""); // NOI18N
        jLabelJugador2.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        jLabelJugador1.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelJugador1.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelJugador1.setName(""); // NOI18N
        jLabelJugador1.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, -1));

        jLabelCrupier10.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier10.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier10.setName(""); // NOI18N
        jLabelCrupier10.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        jLabelCrupier9.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier9.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier9.setName(""); // NOI18N
        jLabelCrupier9.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        jLabelCrupier8.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier8.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier8.setName(""); // NOI18N
        jLabelCrupier8.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jLabelCrupier7.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier7.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier7.setName(""); // NOI18N
        jLabelCrupier7.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabelCrupier6.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier6.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier6.setName(""); // NOI18N
        jLabelCrupier6.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jLabelCrupier5.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier5.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier5.setName(""); // NOI18N
        jLabelCrupier5.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabelCrupier4.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier4.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier4.setName(""); // NOI18N
        jLabelCrupier4.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabelCrupier3.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier3.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier3.setName(""); // NOI18N
        jLabelCrupier3.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabelCrupier2.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier2.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier2.setName(""); // NOI18N
        jLabelCrupier2.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabelCrupier1.setMaximumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier1.setMinimumSize(new java.awt.Dimension(100, 145));
        jLabelCrupier1.setName(""); // NOI18N
        jLabelCrupier1.setPreferredSize(new java.awt.Dimension(100, 145));
        getContentPane().add(jLabelCrupier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBlackjack.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApostarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarManualActionPerformed
        // TODO add your handling code here:
        jButtonPedir.setEnabled(true);
        jButtonPlantarse.setEnabled(true);
        jButtonApostarManual.setEnabled(false);
        jSpinnerApuesta.setEnabled(false);
        juegoManualActual.apostar(Integer.parseInt("" + jSpinnerApuesta.getValue()));
    }//GEN-LAST:event_jButtonApostarManualActionPerformed

    private void jButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirActionPerformed
        // TODO add your handling code here:
        if(juegoManualActual.pedir()){
            jButtonPedir.setEnabled(false);
            jButtonPlantarse.setEnabled(false);
            juegoManualActual.levantarCartaOcultaMaquinote();
            juegoManualActual.ganaMaquina();
            jButtonNuevaApuesta.setVisible(true);
        }
    }//GEN-LAST:event_jButtonPedirActionPerformed

    private void jButtonPlantarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlantarseActionPerformed
        // TODO add your handling code here:
        jButtonPedir.setEnabled(false);
        jButtonPlantarse.setEnabled(false);
        juegoManualActual.jugadaMaquinote();
        juegoManualActual.comprobarGanador();
        jButtonNuevaApuesta.setVisible(true);
    }//GEN-LAST:event_jButtonPlantarseActionPerformed

    public JButton getjButtonNuevaApuestaBot() {
        return jButtonNuevaApuestaBot;
    }

    public JButton getjButtonNuevaApuesta() {
        return jButtonNuevaApuesta;
    }

    private void jButtonNuevaApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaApuestaActionPerformed
        // TODO add your handling code here:
        jButtonNuevaApuesta.setVisible(false);
        jSpinnerApuesta.setEnabled(true);
        jButtonApostarManual.setEnabled(true);
        vaciarLabelsCartas();
        juegoManualActual.nuevaApuesta();
        refrescarPuntuaciones();
    }//GEN-LAST:event_jButtonNuevaApuestaActionPerformed

    private void jButtonApostarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarBotActionPerformed
        // TODO add your handling code here:
        jButtonApostarBot.setEnabled(false);
        jSpinnerApuesta.setEnabled(false);
        juegoBotActual.apostarBot(Integer.parseInt("" + jSpinnerApuesta.getValue()));
    }//GEN-LAST:event_jButtonApostarBotActionPerformed

    private void jButtonNuevaApuestaBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaApuestaBotActionPerformed
        // TODO add your handling code here:
        jButtonNuevaApuestaBot.setEnabled(false);
        jSpinnerApuesta.setEnabled(true);
        jButtonApostarBot.setEnabled(true);
        vaciarLabelsCartas();
        juegoBotActual.nuevaApuesta();
        refrescarPuntuacionesBot();
    }//GEN-LAST:event_jButtonNuevaApuestaBotActionPerformed

    public void refrescarPuntuaciones(){
        jLabelPuntMaquina.setText("" + juegoManualActual.getMaq().getPuntuacion());
        jLabelPuntPerdedor.setText("" + juegoManualActual.getPerd().getPuntuacion());
    }
    
    public void refrescarPuntuacionesBot(){
        jLabelPuntMaquina.setText("" + juegoBotActual.getMaq().getPuntuacion());
        jLabelPuntPerdedor.setText("" + juegoBotActual.getPerd().getPuntuacion());
    }
    
    public void desactivarPedirYPlantarse(){
        jButtonPedir.setEnabled(false);
        jButtonPlantarse.setEnabled(false);
    }
    
    public void actualizarFichas(){
        jLabelFichasJug.setText("" + juegoManualActual.getPerd().getFichas());
    }
    
    public void actualizarFichasBot(){
        jLabelFichasJugBot.setText("" + juegoBotActual.getPerd().getFichas());
    }
    
    public void vaciarLabelsCartas(){
        jLabelCrupier1.setIcon(null);
        jLabelCrupier2.setIcon(null);
        jLabelCrupier3.setIcon(null);
        jLabelCrupier4.setIcon(null);
        jLabelCrupier5.setIcon(null);
        jLabelCrupier6.setIcon(null);
        jLabelCrupier7.setIcon(null);
        jLabelCrupier8.setIcon(null);
        jLabelCrupier9.setIcon(null);
        jLabelCrupier10.setIcon(null);
        jLabelJugador1.setIcon(null);
        jLabelJugador2.setIcon(null);
        jLabelJugador3.setIcon(null);
        jLabelJugador4.setIcon(null);
        jLabelJugador5.setIcon(null);
        jLabelJugador6.setIcon(null);
        jLabelJugador7.setIcon(null);
        jLabelJugador8.setIcon(null);
        jLabelJugador9.setIcon(null);
        jLabelJugador10.setIcon(null);
        
    }
    
    public void juegoBot(int fichas){
        initComponents();
        jButtonPedir.setVisible(false);
        jButtonApostarManual.setVisible(false);
        jButtonPlantarse.setVisible(false);
        jButtonNuevaApuesta.setVisible(false);
        this.setLocationRelativeTo(null);
        this.fichasIniciales = fichas;
        juegoBotActual = new JuegoBot(this);
        actualizarFichasBot();
        jButtonApostarBot.setEnabled(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApostarBot;
    private javax.swing.JButton jButtonApostarManual;
    private javax.swing.JButton jButtonNuevaApuesta;
    private javax.swing.JButton jButtonNuevaApuestaBot;
    private javax.swing.JButton jButtonPedir;
    private javax.swing.JButton jButtonPlantarse;
    private javax.swing.JLabel jLabelCrupier1;
    private javax.swing.JLabel jLabelCrupier10;
    private javax.swing.JLabel jLabelCrupier2;
    private javax.swing.JLabel jLabelCrupier3;
    private javax.swing.JLabel jLabelCrupier4;
    private javax.swing.JLabel jLabelCrupier5;
    private javax.swing.JLabel jLabelCrupier6;
    private javax.swing.JLabel jLabelCrupier7;
    private javax.swing.JLabel jLabelCrupier8;
    private javax.swing.JLabel jLabelCrupier9;
    private javax.swing.JLabel jLabelFichasJug;
    private javax.swing.JLabel jLabelFichasJugBot;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador10;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelJugador3;
    private javax.swing.JLabel jLabelJugador4;
    private javax.swing.JLabel jLabelJugador5;
    private javax.swing.JLabel jLabelJugador6;
    private javax.swing.JLabel jLabelJugador7;
    private javax.swing.JLabel jLabelJugador8;
    private javax.swing.JLabel jLabelJugador9;
    private javax.swing.JLabel jLabelPuntMaquina;
    private javax.swing.JLabel jLabelPuntPerdedor;
    private javax.swing.JLabel jLabelTextFichas;
    private javax.swing.JSpinner jSpinnerApuesta;
    // End of variables declaration//GEN-END:variables
}
